export interface FixRule {
  search: string;
  replace: string;
}

export const FRENCH_RULES: FixRule[] = [
  { search: '\\) - \\[', replace: ') • [' },
  { search: ' - ', replace: ' — ' },
  { search: '  — ', replace: '  - ' },
  { search: '## Pour savoir plus', replace: '## Pour en savoir plus' },
  { search: 'type :', replace: 'type:' },
  { search: 'title :', replace: 'title:' },
  { search: '\\ntitre :', replace: '\ntitle:' },
  { search: '\\ntitre:', replace: '\ntitle:' },
  { search: "\\*\\*L\u2019", replace: "L\u2019**" },
  { search: "\\*\\*L'", replace: "L'**" },
  { search: '\\*\\*La ', replace: 'La **' },
  { search: '\\*\\*Le ', replace: 'Le **' },
  { search: '\\*\\*Les ', replace: 'Les **' },
  { search: '\\*\\*Un ', replace: 'Un **' },
  { search: '\\*\\*Une ', replace: 'Une **' },
  { search: '## Entrées associées \\.', replace: '## Entrées associées' },
  { search: '## Entrées associées\\.', replace: '## Entrées associées' },
  { search: ' "', replace: ' « ' },
  { search: ' » />', replace: '" />' },
  { search: '\u00A0» />', replace: '" />' },
  { search: ' » short />', replace: '" short />' },
  { search: ' » court />', replace: '" short />' },
  { search: '" court />', replace: '" short />' },
  { search: '=« ', replace: '="' },
  { search: '\u00A0» />', replace: '" />' },
  { search: '"\\.', replace: ' ».' },
  { search: '"\\?', replace: ' »?' },
  { search: '"!', replace: ' »!' },
  { search: '":', replace: ' »:' },
  { search: '";', replace: ' »;' },
  { search: '",', replace: ' »,' },
  { search: '"\\)', replace: ' »)' },
  { search: '\\("', replace: '(« ' },
  { search: '\\(\u201C', replace: '(« ' },
  { search: '\\] : <Footnote />', replace: ']: <Footnote />' },
  { search: '\\] : <Sidenote />', replace: ']: <Sidenote />' },
  { search: '\\] \\(\\.', replace: '](.' },
  { search: '\\] \\(htt', replace: '](htt' },
  { search: '\\(\\. /', replace: '(./' },
  { search: '\\. md\\)', replace: '.md)' },
  { search: '\\. \\./', replace: '../' },
  { search: '\\.\\. /', replace: '../' },
  { search: ' :', replace: '\u202F:' },
  { search: ' ;', replace: '\u202F;' },
  { search: ' \\?', replace: '\u202F?' },
  { search: ' !', replace: '\u202F!' },
  { search: ' %', replace: '\u202F%' },
  { search: '\\[\\[', replace: '[' },
  { search: '\\]\\]', replace: ']' },
  { search: '\u201C\\}', replace: '"' },
  { search: '\\{« ', replace: '"' },
  { search: '\\{«', replace: '"' },
  { search: '\u201D\\}', replace: '"' },
  { search: ' »\\}', replace: '"' },
  { search: '»\\}', replace: '"' },
  { search: '>\\.\\s/>', replace: ' />' },
  { search: '"\\}\\)\\.\\s/>', replace: '" />' },
  { search: '"\\} \\}\\)\\.\\s/>', replace: '" />' },
  { search: '=\\{', replace: '=' },
  { search: '\\} />', replace: ' />' },
  { search: '<Note />', replace: '<Footnote />' },
  { search: '"\\}\\.\\s/>', replace: '" />' },
  { search: '"\\[\\^', replace: ' »[^' },
  { search: '«\u00A0', replace: '«\u202F' },
  { search: '\u00A0»', replace: '\u202F»' },
  { search: '«(?!\u202F)', replace: '«\u202F' },
  { search: '(?<!\u202F)»', replace: '\u202F»' },
  { search: '  ', replace: ' ' },
];

export const ITALIAN_RULES: FixRule[] = [
  { search: '\\) - \\[', replace: ') • [' },
  { search: ' - ', replace: ' — ' },
  { search: '  — ', replace: '  - ' },
  { search: '## Voci correlate \\.', replace: '## Voci correlate' },
  { search: '## Voci correlate\\.', replace: '## Voci correlate' },
  { search: '\\] \\(\\.', replace: '](.' },
  { search: '\\] \\(htt', replace: '](htt' },
  { search: '\\. md\\)', replace: '.md)' },
  { search: '\\. \\./', replace: '../' },
  { search: '\\.\\. /', replace: '../' },
  { search: '\\(\\. /', replace: '(./' },
  { search: '\\[\\[', replace: '[' },
  { search: '\\]\\]', replace: ']' },
  { search: '\\{\u201C', replace: '{"' },
  { search: '\u201D\\}', replace: '"}' },
  { search: '>\\.\\s/>', replace: ' />' },
  { search: '"\\}\\)\\.\\s/>', replace: '"} />' },
  { search: '"\\} \\}\\)\\.\\s/>', replace: '"} />' },
  { search: '<Nota />', replace: '<Footnote />' },
  { search: '"\\}\\.\\s/>', replace: '"} />' },
];

export const LANGUAGE_RULES: Record<string, FixRule[]> = {
  fr: FRENCH_RULES,
  it: ITALIAN_RULES,
};
